export default {
  id: "bai",
  priority: 120,
  alias: "bai",
  aliases: ["b-ai", "b.ai"],
  uiAlias: "bai",
  display: {
    name: "B.AI",
    icon: "hub",
    color: "#111827",
    textIcon: "BAI",
    website: "https://b.ai",
    notice: {
      text: "Unified OpenAI-compatible LLM API with multiple model families.",
      apiKeyUrl: "https://chat.b.ai/key",
    },
  },
  category: "apikey",
  authType: "apikey",
  authModes: ["apikey"],
  transport: {
    baseUrl: "https://api.b.ai/v1/chat/completions",
    validateUrl: "https://api.b.ai/v1/models",
    thinkingFormat: "openai",
    usage: {
      url: "https://api.b.ai/v1/balance",
    },
  },
  // Static fallback list (verified across multiple API keys on 2026-09-25 — the
  // catalogue is identical per key) so the dropdown works without a live fetch.
  // modelsFetcher refreshes the list from https://api.b.ai/v1/models on the
  // provider page, and passthroughModels (upstream behaviour) accepts any id
  // beyond this list; add new model IDs here when the upstream catalog changes.
  models: [
    { id: "claude-opus-5.5", name: "Claude Opus 5.5" },
    { id: "claude-opus-5", name: "Claude Opus 5" },
    { id: "claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "claude-fable-5.1", name: "Claude Fable 5.1" },
    { id: "claude-fable-5", name: "Claude Fable 5" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4.1-flash", name: "DeepSeek V4.1 Flash" },
    { id: "gemini-3.8-flash", name: "Gemini 3.8 Flash" },
    { id: "gemini-3.6-flash", name: "Gemini 3.6 Flash" },
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    { id: "gemini-3.5-flash-lite", name: "Gemini 3.5 Flash Lite" },
    { id: "gemini-3.1-pro", name: "Gemini 3.1 Pro" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "glm-5.3", name: "GLM 5.3" },
    { id: "glm-5.3-flash", name: "GLM 5.3 Flash" },
    { id: "glm-5.3-flashx", name: "GLM 5.3 FlashX" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "gpt-6-astra", name: "GPT 6 Astra" },
    { id: "gpt-6-sol", name: "GPT 6 Sol" },
    { id: "gpt-6-luna", name: "GPT 6 Luna" },
    { id: "gpt-5.6-sol", name: "GPT 5.6 Sol" },
    { id: "gpt-5.6-terra", name: "GPT 5.6 Terra" },
    { id: "gpt-5.6-luna", name: "GPT 5.6 Luna" },
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.5-instant", name: "GPT 5.5 Instant" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.4-pro", name: "GPT 5.4 Pro" },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT 5.4 Nano" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5-mini", name: "GPT 5 Mini" },
    { id: "gpt-5-nano", name: "GPT 5 Nano" },
    { id: "gpt-image-2", name: "GPT Image 2" },
    { id: "hy4-preview", name: "Hy4 Preview" },
    { id: "hy3", name: "Hy3" },
    { id: "jev-1.13.0", name: "JEV 1.13.0" },
    { id: "jev-latest", name: "JEV Latest" },
    { id: "kimi-k3", name: "Kimi K3" },
    { id: "kimi-k2.8-preview", name: "Kimi K2.8 Preview" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "minimax-m3", name: "MiniMax M3" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "mimo-v2.6-pro", name: "MIMO V2.6 Pro" },
    { id: "mimo-v2.6-flash", name: "MIMO V2.6 Flash" },
    { id: "mimo-v2.5-pro", name: "MIMO V2.5 Pro" },
    { id: "mimo-v2.5", name: "MIMO V2.5" },
    { id: "qwen3.8-max", name: "Qwen 3.8 Max" },
    { id: "qwen3.8-flash", name: "Qwen 3.8 Flash" },
    { id: "qwen3.8-27b", name: "Qwen 3.8 27B" },
  ],
  modelsFetcher: { url: "https://api.b.ai/v1/models", type: "openai" },
  passthroughModels: true,
  features: {
    usage: true,
    usageApikey: true,
  },
};